// This service simulates the connection to the Liquid Metal Raindrop Backend
// In a real deployment, this would connect to the endpoints generated by:
// npm i -g @liquidmetal-ai/raindrop

import { NetworkMode } from '../types';

interface RaindropNode {
  id: string;
  status: 'ONLINE' | 'OFFLINE';
  latency: number;
  region: string; // e.g., 'us-central-1-metal'
}

export const MOCK_RAINDROP_NODES: RaindropNode[] = [
  { id: 'vbm-man1-1', status: 'ONLINE', latency: 12, region: 'us-east-metal' },
  { id: 'vbm-man1-2', status: 'ONLINE', latency: 14, region: 'us-east-metal' },
  { id: 'vbm-lon1-1', status: 'OFFLINE', latency: 0, region: 'eu-west-metal' },
];

export const checkRaindropHealth = async (): Promise<boolean> => {
  // Simulate a ping to the Liquid Metal Edge endpoint
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, 200);
  });
};

export const syncToEdgeRedis = async (data: any): Promise<boolean> => {
  // Simulate writing to Vultr Managed Redis via Raindrop
  console.log('[Raindrop] Syncing to Edge Redis:', data);
  return true;
};
